name: Koviz Testing Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
      - name: qmake
        run: qmake
      - name: make
        run: make -j3
      - name: koviz -h
        run: ./bin/koviz -h

  build-centos8:
    runs-on: ubuntu-latest
    container: centos:latest
    steps:
      - uses: actions/checkout@master
      - name: install dependencies
        run: |
             sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
             sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
             dnf install -y qt5-qtbase-devel bison flex make gcc gcc-c++
      - name: qmake
        run:  qmake-qt5
      - name: make
        run: make -j3
      - name: koviz -h
        run: ./bin/koviz -h
